services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    restart: always
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aetherbio_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - IS_DOCKER=true
    env_file:
      - ./backend/.env
    depends_on:
      - cockroachdb
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aetherbio_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - IS_DOCKER=true
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cockroach_data:
