import React, { useEffect, useState } from 'react';
import { Sparkles, GitBranch, ShieldCheck, CheckCircle2, ArrowRight } from 'lucide-react';
import { fetchHypotheses } from '../services/api';

export default function HypothesisStudio() {
  const [hypotheses, setHypotheses] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadHypotheses = async () => {
      setLoading(true);
      try {
        const data = await fetchHypotheses();
        setHypotheses(data);
      } catch (err) {
        console.error("Failed to load hypotheses", err);
      } finally {
        setLoading(false);
      }
    };
    loadHypotheses();
  }, []);

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6">
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div>
          <h2 className="text-xl font-bold text-slate-100 flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-amber-400" />
            AI-Synthesized Research Hypotheses
          </h2>
          <p className="text-xs text-slate-400 mt-1">Multi-hop causal discovery automatically generated by reasoning over unlinked publications.</p>
        </div>
      </div>

      {hypotheses.length === 0 ? (
        <div className="glass-panel rounded-2xl p-12 text-center space-y-4 border border-dashed border-slate-800">
          <GitBranch className="w-12 h-12 text-indigo-400 mx-auto opacity-50" />
          <h3 className="text-base font-semibold text-slate-300">No Generated Hypotheses Yet</h3>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Ingest more research papers to allow the Multi-Hop Causal Discovery Engine to uncover indirect connections across domains.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {hypotheses.map((h) => (
            <div key={h.id} className="glass-panel rounded-2xl p-6 border border-slate-800 hover:border-indigo-500/40 transition space-y-4">
              <div className="flex items-start justify-between">
                <span className="px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 flex items-center gap-1">
                  <ShieldCheck className="w-3.5 h-3.5" />
                  {h.confidence_score * 100}% Confidence
                </span>
                <span className="text-xs text-slate-500 uppercase tracking-wider">{h.status}</span>
              </div>

              <h3 className="text-base font-bold text-slate-100">{h.title}</h3>
              <p className="text-xs text-slate-300 leading-relaxed">{h.summary}</p>

              <div className="pt-4 border-t border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500">Causal Chain Hops: {h.causal_path_json?.length || 0}</span>
                <button className="flex items-center space-x-1 text-indigo-400 hover:text-indigo-300 font-semibold">
                  <span>Inspect Evidence Chain</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
